### PR TITLE
feat: moved jx installation to the end

### PR DESCRIPTION
**Pull request by garethjevans**

### CODE REVIEW

**Comment by rawlingsj** [comment]
@garethjevans I've managed to get pretty much all the caching working nicely now, am going to merge and release soon then fix up all the charts so we can trigger all the BDD tests.  I'm just running a cpl more tests but needed to move some base image builds out into https://github.com/jenkins-x/jenkins-x-builders-base.  I'll run through exactly what the changes are when we catch up, although pretty small there will need to be a few things fixed - I've also not sorted updatebot yet either, having said that the builder builds are looking great, not had one fail and are about 35 mins ATM - am trying a cpl more things to get that down just a little more.

For now I'll pop this one on hold as I'm not sure it's needed with the new changes. 
/hold

**Comment by garethjevans** [comment]
No longer required

**Pull request closed without merging**
